apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-pihyg1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pihyg1
  namespace: my-nginx-pihyg1
  labels:
    name: nginx-pihyg1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-pihyg1
  template:
    metadata:
      namespace: my-nginx-pihyg1
      labels:
        name: nginx-pihyg1
    spec:
      containers:
      - name: nginx-pihyg1
        image: nginx
        ports:
        - containerPort: 80

